#!/usr/bin/env bash
# lattice-cell — regenerate every pin. Nothing in pins/ is hand-written.
set -u
HERE=$(cd "$(dirname "$0")" && pwd); ROOT=$(dirname "$HERE")
cd "$ROOT"
STAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)

{
  echo "# lattice-cell crash matrix — regenerated $STAMP"
  echo "# node $(node -v), git $(git --version | awk '{print $3}')"
  echo "# Each row: a child process is killed HARD (exit 137) at one checkpoint."
  echo "# No finally, no atexit, no flush. This is the liveness question measured,"
  echo "# not reasoned about."
  echo
  ./harness/crash-matrix.sh
  echo "## RECONCILIATION AFTER EACH CRASH"
  echo
  for cp in wake dispatch execute commit push outcome; do
    d=${WORK:-/tmp/lattice-crash}/$cp
    printf '%-9s ' "$cp"
    node bin/lattice-cell reconcile --repo "$d/cell" --ledger "$d/ledger.json" 2>/dev/null \
      | node -e "let s='';process.stdin.on('data',d=>s+=d).on('end',()=>{const r=JSON.parse(s);
          const f=(a)=>a.length?a.map(x=>x.id.slice(0,10)+'@'+x.tip.slice(0,7)).join(','):'none';
          console.log('open='+r.openBefore, '| repaired: '+f(r.repaired), '| LOST: '+f(r.abandoned), '| stillOpen='+r.stillOpen);});"
  done
  echo
  echo "## READING THE TABLE"
  echo "  wake     — died before the dispatch row existed. ZERO trace. Unrecoverable"
  echo "             by design, and the reason the DISPATCHER must write the row,"
  echo "             not the cell."
  echo "  dispatch — row is durable, work has not begun. An open lease: re-askable."
  echo "  execute  — same, plus wasted work. Still an open lease."
  echo "  commit   — THE QUESTION IN THE BRIEF. The commit exists in the worktree"
  echo "             and never reached the remote. Reconcile records LOST, a"
  echo "             NEGATIVE receipt. Without it this is indistinguishable from"
  echo "             a clean run. (An earlier version recorded COMMIT here; the"
  echo "             false repair is pinned in bug-false-repair.log and killed"
  echo "             by I11b/I11c.)"
  echo "  push     — the commit IS on the remote; only the outcome was lost."
  echo "             Reconcile repairs it from Dispatch-Id. Recoverable."
  echo "  outcome  — clean."
} > pins/crash-matrix.log

{
  echo "# THE RECEIPT IS A PURE FUNCTION OF THE COMMIT — regenerated $STAMP"
  echo "#"
  echo "# SuperInstance/quilt-adjudication, .quilt/bin/quilt-receipt, cold clone."
  echo "# The claim: a receipt can be DELETED and regenerated byte-identically from"
  echo "# the commit object alone. If true, a lost receipt is a recomputable"
  echo "# condition, not a lost one — which is what lets the lattice treat the"
  echo "# witness log as repairable instead of merely append-only."
  T=$(mktemp -d)
  git clone -q --depth 1 https://github.com/SuperInstance/quilt-adjudication.git "$T/qa" 2>/dev/null
  git init -q "$T/cell"; cd "$T/cell"; git config user.email p@l; git config user.name pin
  cp -r "$T/qa/.quilt" .; chmod +x .quilt/hooks/* .quilt/bin/* 2>/dev/null
  sh .quilt/bin/quilt-init >/dev/null 2>&1
  mkdir -p cells/a/dials; echo "1.0" > cells/a/dials/1; echo "0.8" > cells/a/dials/15
  git add -A; git commit -qm "cell a: obstruction 1.0"
  S=$(git rev-parse --short HEAD)
  echo "  commit $S"; echo "  receipt as written:"; sed 's/^/    /' ".quilt/receipts/$S.json"
  cp ".quilt/receipts/$S.json" /tmp/pin-orig.json
  rm -f ".quilt/receipts/$S.json"
  echo "  DELETED .quilt/receipts/$S.json  ->  dir now: [$(ls .quilt/receipts/)]"
  sh .quilt/bin/quilt-receipt >/dev/null 2>&1
  if cmp -s /tmp/pin-orig.json ".quilt/receipts/$S.json"; then
    echo "  REGENERATED from the commit alone."
    echo "  RESULT: BYTE-IDENTICAL. The receipt is a pure function of the commit."
  else
    echo "  RESULT: DIFFERS — the purity claim is FALSE. See diff:"
    diff /tmp/pin-orig.json ".quilt/receipts/$S.json" | sed 's/^/    /'
  fi
  cd /; rm -rf "$T"
} > pins/purity.log
cd "$ROOT"

{
  echo "# lattice-cell mutation score — regenerated $STAMP"
  echo "# A green suite is not evidence. This is what the suite CONSTRAINS."
  echo "# Rule: a kill requires a real FAIL line. A non-zero exit is NOT a kill —"
  echo "# the first version of this file read one and reported 6/6 for a suite"
  echo "# that had crashed on a missing import. See README and LATTICE.md."
  echo
  node tests/mutation.mjs
} > pins/mutation.log

{
  echo "# THE 64-BIT QUILT WORD HAS NO ARBITRABLE SPEC — regenerated $STAMP"
  echo "# SuperInstance/plato-tile-encoder, src/lib.rs, cold clone."
  echo "# The object type the lattice's word is currently specified by."
  echo
  T=$(mktemp -d); git clone -q --depth 1 https://github.com/SuperInstance/plato-tile-encoder.git "$T/p" 2>/dev/null
  echo "## the two comments, ten lines apart in the same function"
  sed -n '159,175p' "$T/p/src/lib.rs" | sed 's/^/  /'
  echo
  echo "## arithmetic on the doc's own layout"
  node -e 'const f=[64,128,128,32,24,4,4,4],s=f.reduce((a,b)=>a+b,0);
    console.log("  as DOCUMENTED  64+128+128+32+24+4+4+4 =",s,"but the line asserts 384 -> off by",s-384);
    const g=[64,128,128,32,20,4,4,4],t=g.reduce((a,b)=>a+b,0);
    console.log("  as CODED       64+128+128+32+20+4+4+4 =",t,"and the line asserts 384 ->",t===384?"CONSISTENT":"off by "+(t-384));'
  echo
  echo "## consequences, all three measured in the source"
  echo "  1. Follow the DOC and the offsets reach 388 in a 384-byte buffer."
  echo "     The authoritative spec, if obeyed, breaks the type. The code is"
  echo "     right; the specification is wrong; and nothing says so."
  echo "  2. write_str() truncates with min(s,max) and returns no error and no"
  echo "     flag, so tags is silently lossy at 20 bytes. A field that can drop"
  echo "     data without saying so is not a field, it is a hope."
  echo "  3. The doctest asserts_eq!(bytes.len(), 384) — and bytes is a"
  echo "     [u8; BINARY_SIZE] with BINARY_SIZE = 384. It is 384 for ANY input"
  echo "     under ANY layout including a wrong one. THE TEST CANNOT FAIL."
  echo "     This is the 6.8x constant's exact shape: a check that passes at any"
  echo "     value whatsoever."
  echo
  echo "## verdict"
  echo "  A type whose spec cannot add up its own fields cannot arbitrate a"
  echo "  field width, so it cannot be the 64-Bit Quilt Word. This is what the"
  echo "  48-invariant programme in types-REGISTRY.md exists to fix, and the"
  echo "  lattice should treat the word as UNSPECIFIED until it carries a"
  echo "  stated invariant AND a relation that catches a wrong field width."
  rm -rf "$T"
} > pins/quilt-word.log
cd "$ROOT"

echo "pins regenerated:"; wc -c pins/*.log
