from fractions import Fraction as F
import math, struct
def is_exact_binfloat(fr):
    """True iff Fraction is exactly representable as f64 (dyadic)."""
    return fr.denominator & (fr.denominator-1) == 0
rows=[(3,4,5),(5,12,13),(8,15,17),(7,24,25),(20,21,29),(9,40,41),(12,35,37),(11,60,61),
      (28,45,53),(33,56,65),(16,63,65),(48,55,73),(13,84,85),(36,77,85),(39,80,89)]
print(f"{'triple':>14} {'a/c':>22} {'exact?':>7} {'b/c':>22} {'exact?':>7}")
nex=0
for a,b,c in rows:
    x=F(a,c); y=F(b,c)
    ex,ey=is_exact_binfloat(x),is_exact_binfloat(y)
    if not (ex and ey): nex+=1
    print(f"{str((a,b,c)):>14} {str(x):>22} {str(ex):>7} {str(y):>22} {str(ey):>7}")
print(f"\n=> {nex}/15 triples have at least one INEXACT f64 coordinate. (denominator must be power of 2)")
print()
print("=== 'exact integer Pythagorean coordinates' in f64 ===")
print("3/5 =", repr(0.6), " float 0.6 as F =", F(0.6), " == 3/5?", F(0.6)==F(3,5))
print("5/13=", repr(5/13), " F=",F(5/13), " ==5/13?", F(5/13)==F(5,13))
print("-> round-trip through f64 LOSES the rational. Nothing is 'exact' except dyadic cases.")
print()
print("=== sqrt(2)/2 in a 'Pythagorean' table? ===")
s=math.sqrt(2)/2
print("sqrt(2)/2 =", repr(s), "-> F =", F(s), "  (irrational, no finite rational)")
print("If (s,s) were Pythagorean coords we'd need 2s^2 = c^2 -> c = 1, and s = 1/sqrt(2) irrational.")
print("   (s,s) IS on the unit circle but NOT a RATIONAL point. It is NOT generated by any integer triple.")
print()
print("=== does the angle-closure identity hold generally? ===")
print("(bd-ac)^2 + (ad+bc)^2 = (a^2+b^2)(c^2+d^2) = c1^2*c2^2  -> yes, sum of two Pythagorean")
print("angles is Pythagorean. Verify on 3 cases:")
exl=[(3,4,5),(5,12,13),(8,15,17),(7,24,25),(20,21,29)]
import itertools
ok=0; tot=0
for (a,b,e),(cc,d,f) in itertools.combinations(exl,2):
    n,dn=a*d+b*cc, b*d-a*cc
    s=n*n+dn*dn; r=math.isqrt(s)
    tot+=1; ok+= (r*r==s)
    print(f"  ({a},{b})+({cc},{d}) -> ({n},{dn}) hyp={r} perfect={r*r==s}")
print(f"  {ok}/{tot} closed under angle addition.")
